# -*- coding: utf-8 -*-
"""fyp 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojLQruFh62teqjhNH5yEBq02sX_WfPaZ
"""

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/ClassroomActivity"
!ls "$DATASET_PATH"

import os

DATASET_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/ClassroomActivity"

# Step 1 — list all subfolders (labels)
print("🎯 Labels found in dataset:\n")

for folder in sorted(os.listdir(DATASET_PATH)):
    full_path = os.path.join(DATASET_PATH, folder)

    # skip non-folder items (like .zip, .txt)
    if not os.path.isdir(full_path):
        continue

    # count only video files
    video_files = [f for f in os.listdir(full_path) if f.lower().endswith(('.mp4', '.avi', '.mov'))]

    print(f"📂 {folder:25} => {len(video_files)} videos")

# === STEP 1: Import libraries ===
import os
import cv2
import numpy as np
import glob
import tensorflow as tf
from tensorflow.keras import layers, models

# ✅ Labels based on your dataset folders
classes = [
    "Arguing",
    "Eating_in_classroom",
    "Explaining_the_Subject",
    "HandRaise",
    "Holding_Book",
    "Holding_Mobile_Phone",
    "Reading_Book",
    "Sitting_on_Desk",
    "Writing_On_Board",
    "Writting_on_Textbook"
]

print("✅ Environment ready! Total selected labels:", len(classes))
for c in classes:
    print("📂", c)

import tensorflow_hub as hub
import tensorflow as tf

# Load pretrained I3D from TensorFlow Hub
I3D_URL = "https://tfhub.dev/deepmind/i3d-kinetics-400/1"

print("🔹 Loading pretrained I3D model...")
i3d_model = hub.KerasLayer(I3D_URL, trainable=False)
print("✅ I3D model loaded successfully!")

# ===== FULL FIXED I3D TEMPORAL FEATURE EXTRACTION PIPELINE =====
import os, glob
import numpy as np
import cv2
import tensorflow as tf
import tensorflow_hub as hub
from tqdm import tqdm

# optional fast reader
try:
    import imageio.v3 as iio
    IMAGEIO_AVAILABLE = True
except Exception:
    IMAGEIO_AVAILABLE = False

# ---- CONFIG ----
DATASET_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/ClassroomActivity"
FEATURE_SAVE_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/features_fixed"
os.makedirs(FEATURE_SAVE_PATH, exist_ok=True)

TARGET_SIZE = (224, 224)
MAX_FRAMES = 96
WINDOW_SIZE = 16
TIMESTEPS = MAX_FRAMES // WINDOW_SIZE
SAVE_EVERY = 20
VIDEO_EXTS = ('.mp4', '.avi', '.mov', '.mkv')

# ---- WORKING I3D MODEL ----
I3D_URL = "https://tfhub.dev/deepmind/i3d-kinetics-400/1"
print("Loading working I3D model...")
i3d_model = hub.KerasLayer(I3D_URL, trainable=False)

# ---- ROBUST FEATURE EXTRACTOR ----
def extract_feature_safe(window_batch_5d):
    """
    Extract feature for a window: handles different TF-Hub return types.
    window_batch_5d: numpy or tf.Tensor (1, T, H, W, C)
    Returns: 1D numpy array (feat_dim,)
    """
    if not isinstance(window_batch_5d, tf.Tensor):
        window_batch_5d = tf.convert_to_tensor(window_batch_5d, dtype=tf.float32)

    outputs = i3d_model(window_batch_5d)

    # Case A: dict-like
    if isinstance(outputs, dict) or hasattr(outputs, 'get'):
        for key in ("global_pool", "pooled", "feature", "embedding", "default"):
            if key in outputs:
                return tf.squeeze(outputs[key], axis=0).numpy()
        try:
            first_val = next(iter(outputs.values()))
            return tf.squeeze(first_val, axis=0).numpy()
        except Exception:
            pass

    # Case B: tuple/list
    if isinstance(outputs, (list, tuple)):
        for maybe in outputs:
            if isinstance(maybe, (tf.Tensor, np.ndarray)):
                return tf.squeeze(maybe).numpy()
        try:
            return tf.squeeze(tf.convert_to_tensor(outputs)).numpy()
        except Exception:
            pass

    # Case C: single Tensor
    if isinstance(outputs, tf.Tensor):
        return tf.squeeze(outputs).numpy()

    # Fallback
    try:
        return np.squeeze(np.array(outputs))
    except Exception as e:
        raise RuntimeError("Unable to extract feature from I3D output: " + str(e))

# ---- HELPER FUNCTIONS ----
def read_all_frames(video_path, target_size=TARGET_SIZE):
    frames = []
    if IMAGEIO_AVAILABLE:
        try:
            for f in iio.imiter(video_path, plugin="pyav"):
                if f is None:
                    continue
                f = cv2.resize(f, target_size)
                f = f.astype('float32') / 255.0
                frames.append(f)
        except Exception:
            frames = []

    if not frames:
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return []
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            try:
                frame = cv2.resize(frame, target_size)
            except Exception:
                continue
            frame = frame.astype('float32') / 255.0
            frames.append(frame)
        cap.release()
    return frames

def uniform_sample_frames(frames, target_count=MAX_FRAMES):
    n = len(frames)
    if n == 0:
        return None
    if n >= target_count:
        idx = np.linspace(0, n - 1, target_count).astype(int)
        return np.array([frames[i] for i in idx], dtype=np.float32)
    sampled = frames.copy()
    while len(sampled) < target_count:
        sampled.append(sampled[-1])
    return np.array(sampled[:target_count], dtype=np.float32)

def frames_to_windows(sampled_frames, window_size=WINDOW_SIZE):
    windows = []
    for t in range(TIMESTEPS):
        start = t * window_size
        end = start + window_size
        windows.append(sampled_frames[start:end])
    return np.stack(windows, axis=0)  # (TIMESTEPS, WINDOW_SIZE, H, W, C)

# ---- MAIN EXTRACTION LOOP ----
parts = 0
X_batch, y_batch = [], []
total = 0
FEAT_DIM = None

labels = [d for d in sorted(os.listdir(DATASET_PATH)) if os.path.isdir(os.path.join(DATASET_PATH, d))]
print("Found labels:", labels)

for label in labels:
    folder = os.path.join(DATASET_PATH, label)
    videos = [f for f in sorted(os.listdir(folder)) if f.lower().endswith(VIDEO_EXTS)]
    print(f"\nProcessing label: {label} ({len(videos)} videos)")

    for v in tqdm(videos):
        video_path = os.path.join(folder, v)
        try:
            frames = read_all_frames(video_path)
            if not frames:
                print("Skipped:", video_path)
                continue

            sampled = uniform_sample_frames(frames)
            if sampled is None:
                print("Skipped:", video_path)
                continue

            windows = frames_to_windows(sampled)

            feat_list = []
            for w in windows:
                w_batch = np.expand_dims(w, axis=0)
                try:
                    feat_vec = extract_feature_safe(w_batch)
                    # record feature dimension on first run
                    if FEAT_DIM is None:
                        FEAT_DIM = feat_vec.shape[0]
                except Exception as e:
                    print("Feature extraction failed, using zeros:", e)
                    if FEAT_DIM is not None:
                        feat_vec = np.zeros((FEAT_DIM,), dtype=np.float32)
                    else:
                        raise e
                feat_list.append(feat_vec)

            feat_seq = np.stack(feat_list, axis=0)  # (TIMESTEPS, FEAT_DIM)

            X_batch.append(feat_seq)
            y_batch.append(label)
            total += 1

            # Save periodically
            if total % SAVE_EVERY == 0:
                np.save(os.path.join(FEATURE_SAVE_PATH, f"X_part_{parts}.npy"), np.array(X_batch))
                np.save(os.path.join(FEATURE_SAVE_PATH, f"y_part_{parts}.npy"), np.array(y_batch))
                print(f"Saved part {parts}: X_batch shape {np.array(X_batch).shape}")
                parts += 1
                X_batch, y_batch = [], []

        except Exception as e:
            print("Error:", video_path, "->", e)
            continue

# leftover save
if X_batch:
    np.save(os.path.join(FEATURE_SAVE_PATH, f"X_part_{parts}.npy"), np.array(X_batch))
    np.save(os.path.join(FEATURE_SAVE_PATH, f"y_part_{parts}.npy"), np.array(y_batch))
    print(f"Saved final part {parts}")
    parts += 1

print("Extraction done. Total processed:", total)

# ---- MERGE ALL PARTS ----
parts_x = sorted(glob.glob(os.path.join(FEATURE_SAVE_PATH, "X_part_*.npy")))
parts_y = sorted(glob.glob(os.path.join(FEATURE_SAVE_PATH, "y_part_*.npy")))

if parts_x:
    X_all = np.concatenate([np.load(p) for p in parts_x], axis=0)
    y_all = np.concatenate([np.load(p) for p in parts_y], axis=0)
    np.save(os.path.join(FEATURE_SAVE_PATH, "X_features.npy"), X_all)
    np.save(os.path.join(FEATURE_SAVE_PATH, "y_labels.npy"), y_all)
    print("Final features saved.")
    print("X shape:", X_all.shape, "y shape:", y_all.shape)
else:
    print("No parts found to merge!")

import os
FEATURE_SAVE_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/features_fixed"

# List files in the folder to verify
print(os.listdir(FEATURE_SAVE_PATH))

# Load
X = np.load(os.path.join(FEATURE_SAVE_PATH, "X_features.npy"))
y = np.load(os.path.join(FEATURE_SAVE_PATH, "y_labels.npy"))

# === STEP 1: Imports ===
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks

# === STEP 2: Load features and labels ===
FEATURE_SAVE_PATH = "/content/drive/MyDrive/dataset/ClassroomActivity/features_fixed"

X = np.load(FEATURE_SAVE_PATH + "/X_features.npy")  # shape: (914, 6, 400)
y = np.load(FEATURE_SAVE_PATH + "/y_labels.npy")    # shape: (914,)
print(X.shape, y.shape)  # should print (914, 6, 400)

# === STEP 3: Encode labels ===
le = LabelEncoder()
y_encoded = le.fit_transform(y)
num_classes = len(le.classes_)
print("✅ Classes:", le.classes_)

# Convert to categorical
y_cat = tf.keras.utils.to_categorical(y_encoded, num_classes=num_classes)

# === STEP 4: Train-test split ===
X_train, X_val, y_train, y_val = train_test_split(
    X, y_cat, test_size=0.2, random_state=42, stratify=y_encoded
)
print("✅ Training samples:", X_train.shape[0], "Validation samples:", X_val.shape[0])

# === STEP 5: Reshape for LSTM ===
# LSTM expects 3D input: (samples, timesteps, features)
# Our X is already (samples, 6, 400) => no need to reshape
X_train_lstm = X_train
X_val_lstm = X_val
print("✅ LSTM input shape:", X_train_lstm.shape)

# === STEP 6: Build LSTM model ===
model = models.Sequential()
model.add(layers.LSTM(256, input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2]), return_sequences=False))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(num_classes, activation='softmax'))

# === STEP 7: Compile ===
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

# === STEP 8: Callbacks ===
checkpoint_cb = callbacks.ModelCheckpoint(FEATURE_SAVE_PATH + "/lstm_model.h5", save_best_only=True)
earlystop_cb = callbacks.EarlyStopping(patience=10, restore_best_weights=True)

# === STEP 9: Train ===
history = model.fit(
    X_train_lstm, y_train,
    validation_data=(X_val_lstm, y_val),
    epochs=30,
    batch_size=16,
    callbacks=[checkpoint_cb, earlystop_cb]
)

# === STEP 10: Save final model ===
model.save(FEATURE_SAVE_PATH + "/fulfinal_model.h5")
print("✅ Model training complete and saved!")

"""# **MAIN LOGIC FOR VIDEO SUMMERIZATION**"""

# ============================
# 🎯 STEP 1 — IMPORTS
# ============================
import cv2
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from collections import Counter
import os

# ============================
# 🎯 STEP 2 — CONFIG
# ============================
VIDEO_PATH = "/content/drive/MyDrive/c447.mp4"   # 🔴 CHANGE if needed
SAVE_PATH  = "/content/drive/MyDrive/video 00.mp4"

TARGET_SIZE = (224, 224)
MAX_FRAMES = 96
WINDOW_SIZE = 16
TIMESTEPS = MAX_FRAMES // WINDOW_SIZE
CONF_THRESHOLD = 0.5   # 🔥 slightly lower for testing

class_labels = [
    "Arguing","Eating_in_classroom","Explaining_the_Subject",
    "HandRaise","Holding_Book","Holding_Mobile_Phone",
    "Reading_Book","Sitting_on_Desk","Writing_On_Board",
    "Writting_on_Textbook"
]

# ============================
# 🎯 STEP 3 — CHECK VIDEO FILE
# ============================

print("🔍 Checking video path...")

if not os.path.exists(VIDEO_PATH):
    print("❌ Video file NOT found at:", VIDEO_PATH)
    print("👉 Upload video or fix path!")
    exit()

print("✅ Video file found!")

# ============================
# 🎯 STEP 4 — LOAD MODELS
# ============================
print("⏳ Loading models...")

i3d_model = hub.KerasLayer(
    "https://tfhub.dev/deepmind/i3d-kinetics-400/1",
    trainable=False
)

lstm_model = tf.keras.models.load_model(
    "/content/drive/MyDrive/dataset/ClassroomActivity/features_fixed/full_final_model.h5"
)

print("✅ Models loaded!")

# ============================
# 🎯 STEP 5 — HELPER FUNCTIONS
# ============================

def read_frames(cap, start_frame, num_frames):
    frames = []
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    for _ in range(num_frames):
        ret, frame = cap.read()
        if not ret:
            break

        frame = cv2.resize(frame, TARGET_SIZE)
        frame = frame.astype("float32") / 255.0
        frames.append(frame)

    if len(frames) == 0:
        return None

    # repeat last frame
    while len(frames) < MAX_FRAMES:
        frames.append(frames[-1])

    return np.array(frames[:MAX_FRAMES], dtype=np.float32)


def to_windows(frames):
    return np.array([
        frames[i*WINDOW_SIZE:(i+1)*WINDOW_SIZE]
        for i in range(TIMESTEPS)
    ])


def extract_i3d_vec(window):
    window = np.expand_dims(window, axis=0)
    feat = i3d_model(window)
    return tf.squeeze(feat).numpy()


def to_lstm_feature(windows):
    feats = [extract_i3d_vec(w) for w in windows]
    return np.array(feats).reshape(1, TIMESTEPS, -1)

# ============================
# 🎯 STEP 6 — PROCESS VIDEO
# ============================

cap = cv2.VideoCapture(VIDEO_PATH)

if not cap.isOpened():
    print("❌ Cannot open video")
    exit()

total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
FPS = int(cap.get(cv2.CAP_PROP_FPS))

if FPS == 0:
    print("⚠️ FPS issue → using default 30")
    FPS = 30

print(f"🎥 Total Frames: {total_frames}, FPS: {FPS}")

chunk_size = 4 * FPS
pred_segments = []

print("\n⏳ Processing video...")

for start in range(0, total_frames, chunk_size):

    frames = read_frames(cap, start, chunk_size)
    if frames is None:
        continue

    windows = to_windows(frames)
    lstm_input = to_lstm_feature(windows)

    preds = lstm_model.predict(lstm_input, verbose=0)
    label = class_labels[np.argmax(preds)]
    conf  = float(np.max(preds))

    print(f"Segment {start/FPS:.1f}s → {label} ({conf:.2f})")

    if conf >= CONF_THRESHOLD:
        pred_segments.append([label, conf, start, start + chunk_size])

cap.release()

# ============================
# 🎯 STEP 7 — HANDLE EMPTY CASE
# ============================

if len(pred_segments) == 0:
    print("\n❌ No confident segments found!")
    print("👉 Try lowering threshold OR change video")
    exit()

# ============================
# 🎯 STEP 8 — MERGE SEGMENTS
# ============================

merged = []

for seg in pred_segments:
    if not merged:
        merged.append(seg)
    else:
        last = merged[-1]
        if last[0] == seg[0]:
            last[3] = seg[3]
        else:
            merged.append(seg)

pred_segments = merged

# ============================
# 🎯 STEP 9 — TIMELINE SUMMARY
# ============================

print("\n📊 Timeline Summary:\n")

for label, conf, s, e in pred_segments:
    print(f"{s/FPS:.1f}s - {e/FPS:.1f}s → {label} ({conf*100:.1f}%)")

# ============================
# 🎯 STEP 10 — NLP SUMMARY
# ============================

labels_only = [p[0] for p in pred_segments]
top = Counter(labels_only).most_common(2)

summary = "The video mostly shows "

if len(top) == 1:
    summary += top[0][0]
else:
    summary += f"{top[0][0]} and {top[1][0]}"

summary += " activities."

print("\n🧠 AI Summary:")
print(summary)

# ============================
# 🎯 STEP 11 — CREATE VIDEO
# ============================

cap = cv2.VideoCapture(VIDEO_PATH)

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

out = cv2.VideoWriter(SAVE_PATH,
                      cv2.VideoWriter_fourcc(*"mp4v"),
                      FPS, (w, h))

print("\n🎬 Creating summary video...")

for label, conf, s, e in pred_segments:
    cap.set(cv2.CAP_PROP_POS_FRAMES, s)

    for _ in range(s, e):
        ret, frame = cap.read()
        if not ret:
            break

        text = f"{label} ({conf*100:.1f}%)"

        cv2.rectangle(frame, (20, 20), (650, 100), (0,0,0), -1)
        cv2.putText(frame, text, (30, 70),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.5, (0,0,255), 3)

        out.write(frame)

cap.release()
out.release()

print("\n🎉 DONE! Video saved at:", SAVE_PATH)

"""# **FIRST MODULE CODE**"""

import cv2
import numpy as np

# ============================
# 🎯 CONFIG
# ============================

VIDEO_PATH = "/content/drive/MyDrive/c447.mp4"
SAVE_PATH  = "/content/output 0.mp4"

# ============================
# 🎯 LOAD VIDEO
# ============================

cap = cv2.VideoCapture(VIDEO_PATH)

if not cap.isOpened():
    print("❌ Video not found!")
    exit()

FPS = int(cap.get(cv2.CAP_PROP_FPS))
if FPS == 0:
    FPS = 30

frame_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# ============================
# 🎯 VIDEO WRITER
# ============================

out = cv2.VideoWriter(
    SAVE_PATH,
    cv2.VideoWriter_fourcc(*"mp4v"),
    FPS,
    (frame_w, frame_h)
)

# ============================
# 🎯 PERSON DETECTOR
# ============================

hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

# ============================
# 🎯 PROCESS VIDEO
# ============================

teacher_frames = []
prev_gray = None
frame_idx = 0

print("⏳ Processing video...")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # ---- Detect people ----
    boxes, _ = hog.detectMultiScale(frame, winStride=(8,8))

    # ---- Motion detection ----
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    motion_map = None

    if prev_gray is not None:
        motion_map = cv2.absdiff(prev_gray, gray)

    prev_gray = gray

    # ============================
    # 🎯 SELECT ONLY ONE TEACHER
    # ============================

    best_score = -1
    teacher_box = None
    valid_boxes = []

    for (x, y, w, h) in boxes:

        # ❗ Ignore small detections
        if w * h < 4000:
            continue

        valid_boxes.append((x, y, w, h))

        score = 0

        # 1️⃣ Center preference
        center_x = x + w // 2
        if frame_w * 0.3 < center_x < frame_w * 0.7:
            score += 2

        # 2️⃣ Bottom preference (teacher near camera)
        if y > frame_h * 0.4:
            score += 2

        # 3️⃣ Size (larger = closer)
        score += (w * h) / 8000

        # 4️⃣ Motion
        if motion_map is not None:
            person_motion = motion_map[y:y+h, x:x+w]
            if np.sum(person_motion) > 30000:
                score += 1

        # Select best candidate
        if score > best_score:
            best_score = score
            teacher_box = (x, y, w, h)

    # ============================
    # 🎯 DRAW RESULTS
    # ============================

    for (x, y, w, h) in valid_boxes:

        if teacher_box is not None and (x, y, w, h) == teacher_box:
            label = "Teacher"
            color = (0,255,0)
            teacher_frames.append(frame_idx)
        else:
            label = "Student"
            color = (255,0,0)

        cv2.rectangle(frame, (x,y), (x+w,y+h), color, 2)
        cv2.putText(frame, label, (x,y-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.7, color, 2)

    # ---- Save frame ----
    out.write(frame)
    frame_idx += 1

cap.release()
out.release()

print("✅ Video saved at:", SAVE_PATH)

# ============================
# 🎯 PUNCTUALITY
# ============================

print("\n⏰ Punctuality Result:\n")

if len(teacher_frames) > 0:

    arrival_time = min(teacher_frames) / FPS
    departure_time = max(teacher_frames) / FPS

    print(f"📌 Arrival Time: {arrival_time:.2f} sec")
    print(f"📌 Departure Time: {departure_time:.2f} sec")

    CLASS_START = 0
    CLASS_END = total_frames / FPS
    GRACE = 10

    if arrival_time <= CLASS_START + GRACE:
        arrival_status = "On-Time"
    else:
        arrival_status = "Late"

    if departure_time >= CLASS_END - GRACE:
        departure_status = "Full Duration"
    else:
        departure_status = "Early Leave"

    if arrival_status == "On-Time" and departure_status == "Full Duration":
        final_status = "ON-TIME"
    elif arrival_status == "Late":
        final_status = "LATE ARRIVAL"
    elif departure_status == "Early Leave":
        final_status = "EARLY LEAVE"
    else:
        final_status = "IRREGULAR"

    print("\n📊 Final Status:", final_status)

else:
    print("❌ Teacher not detected → ABSENT")